/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class JNITestClass */

#ifndef _Included_JNITestClass
#define _Included_JNITestClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNITestClass
 * Method:    doNothing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNITestClass_doNothing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
